name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: write # Ensures write access for deployment
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variable: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      - name: Set Environment Variable: GITHUB_ACTOR
        run: echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV

      - name: Set Environment Variable: GITHUB_REPOSITORY
        run: echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v3 # Use the latest stable version
        with:
          persist-credentials: false # Required for proper deployment in some configurations

      - name: Read CNAME
        id: cname
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CNAME

      - name: Set Environment Variable: CNAME
        run: echo "CNAME=${{ steps.cname.outputs.content }}" >> $GITHUB_ENV

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch to deploy to
          folder: public # The folder containing the build output
          cname: ${{ steps.cname.outputs.content }}
